### ISSUE TITLE
项目序列化和反序列化

### ISSUE THREAD

**Issue by c77777771** [yoi102/VisionProcess#1]
想请教下这个项目，整体的序列化和反序列化得怎么做比较好？

**Comment by yoi102** [comment]
已经上传序列化和反序列化版本，操作在App.xaml.cs的OnStartup和OnExit 方法中，

**Comment by yoi102** [comment]
对于一些模块添加了 JsonConstructor ，目前还清楚怎么序列化Mat和BitmapSource更好，希望能对你有所帮助。
如果知道更好的序列化方式，还请联系告诉我，谢谢

**Comment by c77777771** [comment]
我反序列化的时候，它进默认构造函数，这是啥原因？
![6f5e1903e0c0c644feadcffc4da7f70](https://github.com/yoi102/VisionProcess/assets/54462138/1aa97774-76f3-4631-ab29-cded92207e52)

**Comment by yoi102** [comment]
请确认下 [JsonConstructor] 的命名空间，和构造器的参数名称是否和属性名称相匹配

**Comment by c77777771** [comment]
我构造器的参数名称和属性名称是相匹配。我发现问题了，是如果你用了这个。应该是最外层开始都要用 [JsonConstructor]。比如说ClassA   下有 ClassB 下有 ClassC。我现在是ClassA没用，就ClassB、ClassC用了，不行。我现在把ClassA也加了，就进去了。
